FROM node:14.16.0-alpine3.13 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Step 2: Production
FROM nginx:1.12-alpine 
RUN addgroup app && adduser -S -G app app
RUN mkdir /app && chown app:app /app
USER app

ENV API_URL=http://localhost:5000/api

COPY --from=build-stage /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
