FROM node:14.16.0-alpine3.13 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
#url production
ENV REACT_APP_API_URL=http://104.131.24.150:3001/api 
RUN npm run build

# Step 2: Production
FROM nginx:1.12-alpine 
EXPOSE 80
COPY --from=build-stage /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
