version: '3.8'

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfle.prod
    ports:
      - 80:80
    restart: unless-stopped
  api:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgres://postgres:123@127.0.0.1:5432/resi-book_postgres
    command: npm run dev
    restart: unless-stopped
  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5432
    volumes:
      - resi-book:/data/db
    restart: unless-stopped

volumes:
  resi-book:
