version: '3.8'

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfle.prod
    ports:
      - 80:80
    restart: unless-stopped
  api:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: 
    command: npm run dev
    restart: unless-stopped
  postgres:
    image: postgres:13-alpine
    ports:
      - 49158:5432
    volumes:
      - resi-book:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  resi-book:
