version: '3.8'

services:
  web:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
  api:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgres://postgres:123@127.0.0.1:5432/backend_resi-book
    command: npm run dev
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432
    volumes:
      - resi-book:/var/lib/postgresql/data

volumes:
  resi-book:
