version: '3.8'

services:
  api:
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./app
    environment:
      DATABASE_URL: postgres://postgres:123@127.0.0.1:49158/backend_resi-book
    command: npm run dev
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432
    volumes:
      - resi-book:/var/lib/postgresql/data

volumes:
  resi-book:
